# permissions for end users to edit ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-editor-role
rules:
- apiGroups:
  - networking.stevesloka.com
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stevesloka.com
  resources:
  - ingresses/status
  verbs:
  - get
