# permissions for end users to view ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-viewer-role
rules:
- apiGroups:
  - networking.stevesloka.com
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.stevesloka.com
  resources:
  - ingresses/status
  verbs:
  - get
